eureka:
    client:
        fetch-registry: false
        register-with-eureka: false
        service-url:
            defalutZone: http://eureka1:8000/eureka, http://eureka2:8000/eureka
server:
    port: 8000
    tomcat:
        max-threads: 5 # tomcat最大并发量
spring:
    application:
        name: eureka-server
logging:
    pattern:
        file: '%clr(%d{${LOG_DATEFORMAT_PATTERN:HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p})
                    %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan}
                    %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}'
    file: app.log
    path: /springboot/log